#!/usr/bin/env bash
# ExFAT (this checkout's volume) stores AppleDouble `._*` next to every file.
# tauri 2.11.5 build.rs globs autogenerated permission TOMLs and panics:
#   failed to read .../autogenerated/._default.toml: stream did not contain valid UTF-8
# Keep rustc's target dir on APFS so those sidecars are never created there.
# CI already has a real target dir — do not override CARGO_TARGET_DIR if set.
set -euo pipefail
if [ -z "${CARGO_TARGET_DIR:-}" ]; then
  export CARGO_TARGET_DIR="${NAPI_CARGO_TARGET_DIR:-${HOME}/.cache/napi-desktop/target}"
fi
mkdir -p "${CARGO_TARGET_DIR}"
exec "$@"
